id: I2AA47228
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:04:59+00:00'
last_modified: '2022-06-08T08:32:25.887410+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3119
  title: མདོ་སྡེ་སྐལ་བཟང་དང་བརྒྱད་སྟོང་གཟུངས་བསྡུས་བཅས་སྣར་ཐང་པར་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4B14:
      image_group_id: I3CN3136
      title: ''
      total_pages: 930
      order: 1
      base_file: 4B14.txt
    '8063':
      image_group_id: I3CN3137
      title: ''
      total_pages: 1140
      order: 2
      base_file: 8063.txt
    C158:
      image_group_id: I3CN3138
      title: ''
      total_pages: 1101
      order: 3
      base_file: C158.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
