id: I2AA47228
legacy_id: P009089
ocr_import_info:
  bdrc_scan_id: W3CN3119
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T19:57:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:21:16.305497+00:00'
last_modified: 2022-09-03 21:23:49.418707
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3119
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3119
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་སྡེ་སྐལ་བཟང་དང་བརྒྱད་སྟོང་གཟུངས་བསྡུས་བཅས་སྣར་ཐང་པར་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7190217799389652
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I3CN3136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3136
      total_pages: 930
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3136.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7014586275064761
    legacy_id: v001
  I3CN3137:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3137
      total_pages: 1140
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3137.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7295664641254335
    legacy_id: v002
  I3CN3138:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3138
      total_pages: 1101
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN3138.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7210086138677941
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
